In [81]:
import pandas as pd
Link= "https://docs.google.com/spreadsheets/d/e/2PACX-1vSDv2t5CItYWZccOernOptZZGeEMKJumHRMyGgKgaa2VLrbf6V3c1VVak89Sfz8VA/pubhtml"

In [102]:
hdi=pd.read_html(Link)[0]
hdi

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,1.0,Back,Table 1. Human Development Index and its compo...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3.0,NaN,NaN,NaN,NaN,NaN,SDG3,NaN,SDG4.3,NaN,SDG4.4,NaN,SDG8.5,NaN,NaN,NaN,NaN
3,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,NaN,NaN,NaN,Human Development Index (HDI),NaN,Life expectancy at birth,NaN,Expected years of schooling,NaN,Mean years of schooling,NaN,Gross national income (GNI) per capita,NaN,GNI per capita rank minus HDI rank,NaN,HDI rank
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
273,273.0,NaN,Column 2: UNDESA (2022a).,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
274,274.0,NaN,"Column 3: CEDLAS and World Bank (2022), ICF Ma...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
275,275.0,NaN,"Column 4: Barro and Lee (2018), ICF Macro Demo...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
276,276.0,NaN,"Column 5: IMF (2022), UNDESA (2022b), United N...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
277,277.0,NaN,Column 6: Calculated based on data in columns ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [103]:
hdi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 278 entries, 0 to 277
Data columns (total 17 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   277 non-null    float64
 1   Unnamed: 1   193 non-null    object
 2   Unnamed: 2   262 non-null    object
 3   Unnamed: 3   5 non-null      object
 4   Unnamed: 4   218 non-null    object
 5   Unnamed: 5   5 non-null      object
 6   Unnamed: 6   219 non-null    object
 7   Unnamed: 7   6 non-null      object
 8   Unnamed: 8   219 non-null    object
 9   Unnamed: 9   106 non-null    object
 10  Unnamed: 10  219 non-null    object
 11  Unnamed: 11  92 non-null     object
 12  Unnamed: 12  219 non-null    object
 13  Unnamed: 13  16 non-null     object
 14  Unnamed: 14  217 non-null    object
 15  Unnamed: 15  6 non-null      object
 16  Unnamed: 16  212 non-null    object
dtypes: float64(1), object(16)
memory usage: 37.0+ KB

In [110]:
keep=[1,2,4,6,8,10,12,14,16]  # números de columnas que deseas mantener
dontKeep=set(hdi.columns.to_list())-set(hdi.columns[keep])
hdiCleaned=hdi.drop(columns=dontKeep)

hdiCleaned

,Unnamed: 1,Unnamed: 2,Unnamed: 4,Unnamed: 6,Unnamed: 8,Unnamed: 10,Unnamed: 12,Unnamed: 14,Unnamed: 16
0,Back,Table 1. Human Development Index and its compo...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,SDG3,SDG4.3,SDG4.4,SDG8.5,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank,HDI rank
...,...,...,...,...,...,...,...,...,...
273,NaN,Column 2: UNDESA (2022a).,NaN,NaN,NaN,NaN,NaN,NaN,NaN
274,NaN,"Column 3: CEDLAS and World Bank (2022), ICF Ma...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
275,NaN,"Column 4: Barro and Lee (2018), ICF Macro Demo...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
276,NaN,"Column 5: IMF (2022), UNDESA (2022b), United N...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
277,NaN,Column 6: Calculated based on data in columns ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [142]:
hdihdi=hdiCleaned[9:203]
hdihdi

,Unnamed: 1,Unnamed: 2,Unnamed: 4,Unnamed: 6,Unnamed: 8,Unnamed: 10,Unnamed: 12,Unnamed: 14,Unnamed: 16
9,1,Switzerland,0962,840,165,139,66.933,5,3
10,2,Norway,0961,832,182,130,64.660,6,1
11,3,Iceland,0959,827,192,138,55.782,11,2
12,4,"Hong Kong, China (SAR)",0952,855,173,122,62.607,6,4
13,5,Australia,0951,845,211,127,49.238,18,5
...,...,...,...,...,...,...,...,...,...
198,187,Burundi,0426,617,107,31,732,4,187
199,188,Central African Republic,0404,539,80,43,966,1,188
200,189,Niger,0400,616,70,21,1.240,-3,189
201,190,Chad,0394,525,80,26,1.364,-7,190
202,191,South Sudan,0385,550,55,57,768,-1,191

In [143]:
change1={'Unnamed: 1':"HDI Rank"}
hdihdi.rename(columns=change1,inplace=True)
hdihdi
change2={'Unnamed: 2':"Country"}
hdihdi.rename(columns=change2,inplace=True)
hdihdi
change3={'Unnamed: 4':"Human Development Index (HDI) 2021"}
hdihdi.rename(columns=change3,inplace=True)
hdihdi
change4={'Unnamed: 6':"Life expectancy at birth 2021"}
hdihdi.rename(columns=change4,inplace=True)
hdihdi
change5={'Unnamed: 8':"Expected years of schooling - 2021"}
hdihdi.rename(columns=change5,inplace=True)
hdihdi
change6={'Unnamed: 10':"Mean years of schooling - 2021"}
hdihdi.rename(columns=change6,inplace=True)
hdihdi
change7={'Unnamed: 12':"Gross national income (GNI) per capita - 2021"}
hdihdi.rename(columns=change7,inplace=True)
hdihdi
change8={'Unnamed: 14':"GNI per capita rank minus HDI rank - 2021"}
hdihdi.rename(columns=change8,inplace=True)
hdihdi
change9={'Unnamed: 16':"HDI RANK - 2020"}
hdihdi.rename(columns=change9,inplace=True)
hdihdi

<ipython-input-143-a857f2741258>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hdihdi.rename(columns=change1,inplace=True)
<ipython-input-143-a857f2741258>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hdihdi.rename(columns=change2,inplace=True)
<ipython-input-143-a857f2741258>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hdihdi.rename(columns=change3,inplace=True)
<ipython-input-143-a857f2741258>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hdihdi.rename(columns=change4,inplace=True)
<ipython-input-143-a857f2741258>:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hdihdi.rename(columns=change5,inplace=True)
<ipython-input-143-a857f2741258>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hdihdi.rename(columns=change6,inplace=True)
<ipython-input-143-a857f2741258>:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hdihdi.rename(columns=change7,inplace=True)
<ipython-input-143-a857f2741258>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hdihdi.rename(columns=change8,inplace=True)
<ipython-input-143-a857f2741258>:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hdihdi.rename(columns=change9,inplace=True)

,HDI Rank,Country,Human Development Index (HDI) 2021,Life expectancy at birth 2021,Expected years of schooling - 2021,Mean years of schooling - 2021,Gross national income (GNI) per capita - 2021,GNI per capita rank minus HDI rank - 2021,HDI RANK - 2020
9,1,Switzerland,0962,840,165,139,66.933,5,3
10,2,Norway,0961,832,182,130,64.660,6,1
11,3,Iceland,0959,827,192,138,55.782,11,2
12,4,"Hong Kong, China (SAR)",0952,855,173,122,62.607,6,4
13,5,Australia,0951,845,211,127,49.238,18,5
...,...,...,...,...,...,...,...,...,...
198,187,Burundi,0426,617,107,31,732,4,187
199,188,Central African Republic,0404,539,80,43,966,1,188
200,189,Niger,0400,616,70,21,1.240,-3,189
201,190,Chad,0394,525,80,26,1.364,-7,190
202,191,South Sudan,0385,550,55,57,768,-1,191

In [144]:
objectCols=hdihdi.select_dtypes(include=['object']).columns
objectCols

Index(['HDI Rank', 'Country', 'Human Development Index (HDI) 2021',
       'Life expectancy at birth 2021', 'Expected years of schooling - 2021',
       'Mean years of schooling - 2021',
       'Gross national income (GNI) per capita - 2021',
       'GNI per capita rank minus HDI rank - 2021', 'HDI RANK - 2020'],
      dtype='object')

In [145]:
hdihdi.loc[:,objectCols]=hdihdi.loc[:,objectCols].apply(lambda col:col.str.strip())
hdihdi

<ipython-input-145-9efcfe9029da>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hdihdi.loc[:,objectCols]=hdihdi.loc[:,objectCols].apply(lambda col:col.str.strip())

,HDI Rank,Country,Human Development Index (HDI) 2021,Life expectancy at birth 2021,Expected years of schooling - 2021,Mean years of schooling - 2021,Gross national income (GNI) per capita - 2021,GNI per capita rank minus HDI rank - 2021,HDI RANK - 2020
9,1,Switzerland,0962,840,165,139,66.933,5,3
10,2,Norway,0961,832,182,130,64.660,6,1
11,3,Iceland,0959,827,192,138,55.782,11,2
12,4,"Hong Kong, China (SAR)",0952,855,173,122,62.607,6,4
13,5,Australia,0951,845,211,127,49.238,18,5
...,...,...,...,...,...,...,...,...,...
198,187,Burundi,0426,617,107,31,732,4,187
199,188,Central African Republic,0404,539,80,43,966,1,188
200,189,Niger,0400,616,70,21,1.240,-3,189
201,190,Chad,0394,525,80,26,1.364,-7,190
202,191,South Sudan,0385,550,55,57,768,-1,191

In [148]:
hdihdi['Life_expectancy_at_birth_2021'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 194 entries, 9 to 202
Series name: Life_expectancy_at_birth_2021
Non-Null Count  Dtype
--------------  -----
194 non-null    object
dtypes: object(1)
memory usage: 1.6+ KB

In [149]:
hdihdi.columns=hdihdi.columns.str.replace('\s','_',regex=True)
hdihdi

,HDI_Rank,Country,Human_Development_Index_(HDI)_2021,Life_expectancy_at_birth_2021,Expected_years_of_schooling_-_2021,Mean_years_of_schooling_-_2021,Gross_national_income_(GNI)_per_capita_-_2021,GNI_per_capita_rank_minus_HDI_rank_-_2021,HDI_RANK_-_2020
9,1,Switzerland,0962,840,165,139,66.933,5,3
10,2,Norway,0961,832,182,130,64.660,6,1
11,3,Iceland,0959,827,192,138,55.782,11,2
12,4,"Hong Kong, China (SAR)",0952,855,173,122,62.607,6,4
13,5,Australia,0951,845,211,127,49.238,18,5
...,...,...,...,...,...,...,...,...,...
198,187,Burundi,0426,617,107,31,732,4,187
199,188,Central African Republic,0404,539,80,43,966,1,188
200,189,Niger,0400,616,70,21,1.240,-3,189
201,190,Chad,0394,525,80,26,1.364,-7,190
202,191,South Sudan,0385,550,55,57,768,-1,191

In [153]:
hdihdi['HDI_Rank']=pd.to_numeric(hdihdi.HDI_Rank)

<ipython-input-153-c5fbbd1811dd>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hdihdi['HDI_Rank']=pd.to_numeric(hdihdi.HDI_Rank)

In [154]:
hdihdi['HDI_Rank'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 194 entries, 9 to 202
Series name: HDI_Rank
Non-Null Count  Dtype
--------------  -----
191 non-null    float64
dtypes: float64(1)
memory usage: 1.6 KB

In [155]:
hdihdi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 194 entries, 9 to 202
Data columns (total 9 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   HDI_Rank                                       191 non-null    float64
 1   Country                                        194 non-null    object
 2   Human_Development_Index_(HDI)_2021             194 non-null    object
 3   Life_expectancy_at_birth_2021                  194 non-null    object
 4   Expected_years_of_schooling_-_2021             194 non-null    object
 5   Mean_years_of_schooling_-_2021                 194 non-null    object
 6   Gross_national_income_(GNI)_per_capita_-_2021  194 non-null    object
 7   GNI_per_capita_rank_minus_HDI_rank_-_2021      194 non-null    object
 8   HDI_RANK_-_2020                                191 non-null    object
dtypes: float64(1), object(8)
memory usage: 13.8+ KB

In [156]:
import os

os.mkdir('prueba_pc2')

hdihdi.to_csv(os.path.join("prueba_pc2","hdihdi.csv"),index=False)

FileExistsError: [Errno 17] File exists: 'prueba_pc2'